// Frontend contract tests (PRD Testing Decisions).
//
// The fixture is generated by `cargo run -p keyplane-core --example dump_dtos`,
// so these assert against the exact serde shape Rust emits, not hand-authored
// JSON. They verify the overlay receives selected values, confidence, active
// layer, and backend health without depending on any protocol API.

import { describe, expect, it } from "vitest";
import dtos from "./__fixtures__/dtos.json";
import { applyEvent, collapseLegend, initialState, topLayer } from "./overlayState";
import type { KeyboardSnapshot, ResolvedKey, RuntimeEvent } from "./types";

const snapshot = dtos.snapshot as unknown as KeyboardSnapshot;
const navEvent = dtos.navEvent as unknown as RuntimeEvent;
const healthEvent = dtos.healthEvent as unknown as RuntimeEvent;

describe("snapshot contract", () => {
  it("carries a fully resolved keyboard", () => {
    expect(snapshot.schema).toBe(1);
    expect(snapshot.keys).toHaveLength(16);
    expect(snapshot.layers).toHaveLength(3);
    expect(snapshot.backends[0].health.state).toBe("ok");
  });

  it("starts on the base layer", () => {
    expect(topLayer(snapshot.layer_stack)).toBe("layer-0");
  });
});

describe("applyEvent", () => {
  it("swaps re-resolved keys on a layer-stack event", () => {
    const next = applyEvent(initialState(snapshot), navEvent);
    expect(topLayer(next.snapshot.layer_stack)).toBe("layer-1");

    // A defined top-layer key renders its own value, not inherited.
    const k0 = findKey(next.snapshot.keys, "k0");
    expect(k0.effective).toMatchObject({ kind: "key", label: "1" });
    expect(k0.inherited).toBe(false);

    // A transparent key inherits from the base layer and is flagged.
    const k8 = findKey(next.snapshot.keys, "k8");
    expect(k8.inherited).toBe(true);
    expect(k8.source_layer).toBe("layer-0");
  });

  it("does not mutate the previous state", () => {
    const start = initialState(snapshot);
    const before = start.snapshot.confidence;
    applyEvent(start, navEvent);
    expect(start.snapshot.confidence).toBe(before);
  });

  it("flows backend health into the snapshot", () => {
    const next = applyEvent(initialState(snapshot), healthEvent);
    expect(next.snapshot.backends[0].health.state).toBe("disconnected");
  });
});

describe("collapseLegend", () => {
  it("prefers the tap role for tap-hold keys", () => {
    const key = {
      legend: { tap: "Space", hold: "Ctrl" },
    } as unknown as ResolvedKey;
    expect(collapseLegend(key)).toBe("Space");
  });

  it("falls back to the primary label", () => {
    const key = findKey(snapshot.keys, "k0");
    expect(collapseLegend(key)).toBe(key.legend.primary);
  });
});

function findKey(keys: ResolvedKey[], id: string): ResolvedKey {
  const key = keys.find((k) => k.key === id);
  if (!key) throw new Error(`missing key ${id}`);
  return key;
}
